Repository explosion/spacy-legacy, pull requests merged in 2022-12, with the labels that each got.

#26 Replace removed error message with hard-coded text
  spacy_legacy/loggers.py
Labels: bug

#32 Add `ConsoleLogger.v2`
  setup.cfg
  spacy_legacy/loggers.py
  spacy_legacy/tests/test_legacy.py
Labels: enhancement

#34 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
